# syntax=docker/dockerfile:1
FROM golang:1.22-alpine AS build
WORKDIR /src
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/smh-core ./cmd/smh-core

FROM alpine:3.20
WORKDIR /app
COPY --from=build /out/smh-core ./smh-core
ENV MQTT_URL=tcp://mqtt:1883
ENTRYPOINT ["./smh-core"]
