// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	mqtt2 "github.com/tetragramaton/smh-go/internal/client/mqtt"
	"github.com/tetragramaton/smh-go/internal/interface/mqtt"
)

// Injectors from wire.go:

func InitMainHandler() (*MainHandler, error) {
	client, err := ProvideMqttClient()
	if err != nil {
		return nil, err
	}
	mainHandler := NewMainHandler(client)
	return mainHandler, nil
}

// wire.go:

type MainHandler struct {
	MQQTClient mqtt.Client
}

func NewMainHandler(
	mqttClient mqtt.Client,
) *MainHandler {
	return &MainHandler{
		MQQTClient: mqttClient,
	}
}

func ProvideMqttClient() (mqtt.Client, error) {
	return mqtt2.NewClient()
}
