// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	modbus2 "github.com/tetragramaton/smh-go/internal/client/modbus"
	mqtt2 "github.com/tetragramaton/smh-go/internal/client/mqtt"
	"github.com/tetragramaton/smh-go/internal/interface/modbus"
	"github.com/tetragramaton/smh-go/internal/interface/mqtt"
)

// Injectors from wire.go:

func InitMainHandler() (*MainHandler, error) {
	client, err := ProvideMqttClient()
	if err != nil {
		return nil, err
	}
	modbusClient, err := ProvideNewModbusClient()
	if err != nil {
		return nil, err
	}
	mainHandler := NewMainHandler(client, modbusClient)
	return mainHandler, nil
}

// wire.go:

type MainHandler struct {
	MQQTClient   mqtt.Client
	ModbusClient modbus.Client
}

func NewMainHandler(mqttClient2 mqtt.Client,

	modbusClient modbus.Client,
) *MainHandler {
	return &MainHandler{
		MQQTClient:   mqttClient2,
		ModbusClient: modbusClient,
	}
}

func ProvideMqttClient() (mqtt.Client, error) {
	return mqtt2.NewClient()
}

func ProvideNewModbusClient() (modbus.Client, error) {
	return modbus2.NewHandler()
}
